### ISSUE TITLE
Update matters lab

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-lab-svelte-site#2]
### Tasks
- [x] remove medium from `follow us` section in home page
- [x] remove medium from footer
- [x] hamburger menu is still open after click blog on mobile device
- [x] update 404 error message
- [x] change copy `Frontline Award` to `Frontline Fellowship for Chinese Non-Fiction Writing`

### References
- [Design](https://www.figma.com/file/uRIEtwGCvFUfgGl2x1uepG/Matters.Lab?node-id=0%3A1)
- [Copy doc](https://paper.dropbox.com/doc/Matters-Lab-Landing-Page--Bq2DzY2zbhcZVSXwRoRLL37qAg-lPml6GpxHfRbH6juLpMxp)

**Comment by devformatters** [comment]
I've added two more minor tasks: menu bug & copy change

**Comment by devformatters** [comment]
@tx0c 

1.
> remove medium from footer

There's still a weird space

<img width="55%" src="https://user-images.githubusercontent.com/34237112/195800963-dd7115da-6886-4522-b794-147c89b7739e.png">


2.
> update 404 error message

Please follow [design](https://www.figma.com/file/uRIEtwGCvFUfgGl2x1uepG/Matters.Lab?node-id=0%3A1)
