### ISSUE TITLE
Update blog main page

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-lab-svelte-site#3]
### Tasks
- [x] update main block by design
  - block composed by 3 components: cover, content, entry button
  - all 3 components should be clickable
- [x] fix main block width is different from others
- [x] update header of article list
- [x] update article cards by design

### References
- [Design](https://www.figma.com/file/uRIEtwGCvFUfgGl2x1uepG/Matters.Lab?node-id=0%3A1)
