### ISSUE TITLE
Update blog article page

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-lab-svelte-site#4]
### Tasks
- [x] update article page navigation background (no gradient background)
- [x] adjust width of article block
- [x] adjust title, font and images styles and spacings

### References
- [Design](https://www.figma.com/file/uRIEtwGCvFUfgGl2x1uepG/Matters.Lab?node-id=754%3A76)
